/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StroomstoringAmsterdamRouteImport } from './routes/stroomstoring-amsterdam'
import { Route as SpoedElektricienAmsterdamRouteImport } from './routes/spoed-elektricien-amsterdam'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PostocodeCheckRouteImport } from './routes/postocode-check'
import { Route as PerilexAmsterdamRouteImport } from './routes/perilex-amsterdam'
import { Route as PerilexAansluitenAmsterdamRouteImport } from './routes/perilex-aansluiten-amsterdam'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as OnzeServicesRouteImport } from './routes/onze-services'
import { Route as GroepenkastVervangenAmsterdamRouteImport } from './routes/groepenkast-vervangen-amsterdam'
import { Route as EnGbRouteImport } from './routes/en-gb'
import { Route as ElektricienAmsterdamRouteImport } from './routes/elektricien-amsterdam'
import { Route as ElektricienRouteImport } from './routes/elektricien'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GroepenkastAmsterdamRouteImport } from './routes/Groepenkast-Amsterdam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnGbIndexRouteImport } from './routes/en-gb.index'
import { Route as EnGbStroomstoringAmsterdamRouteImport } from './routes/en-gb.stroomstoring-amsterdam'
import { Route as EnGbSpoedElektricienAmsterdamRouteImport } from './routes/en-gb.spoed-elektricien-amsterdam'
import { Route as EnGbPerilexAmsterdamRouteImport } from './routes/en-gb.perilex-amsterdam'
import { Route as EnGbOverOnsRouteImport } from './routes/en-gb.over-ons'
import { Route as EnGbGroepenkastVervangenAmsterdamRouteImport } from './routes/en-gb.groepenkast-vervangen-amsterdam'
import { Route as EnGbElektricienAmsterdamRouteImport } from './routes/en-gb.elektricien-amsterdam'
import { Route as EnGbContactRouteImport } from './routes/en-gb.contact'

const StroomstoringAmsterdamRoute = StroomstoringAmsterdamRouteImport.update({
  id: '/stroomstoring-amsterdam',
  path: '/stroomstoring-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoedElektricienAmsterdamRoute =
  SpoedElektricienAmsterdamRouteImport.update({
    id: '/spoed-elektricien-amsterdam',
    path: '/spoed-elektricien-amsterdam',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostocodeCheckRoute = PostocodeCheckRouteImport.update({
  id: '/postocode-check',
  path: '/postocode-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PerilexAmsterdamRoute = PerilexAmsterdamRouteImport.update({
  id: '/perilex-amsterdam',
  path: '/perilex-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const PerilexAansluitenAmsterdamRoute =
  PerilexAansluitenAmsterdamRouteImport.update({
    id: '/perilex-aansluiten-amsterdam',
    path: '/perilex-aansluiten-amsterdam',
    getParentRoute: () => rootRouteImport,
  } as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const OnzeServicesRoute = OnzeServicesRouteImport.update({
  id: '/onze-services',
  path: '/onze-services',
  getParentRoute: () => rootRouteImport,
} as any)
const GroepenkastVervangenAmsterdamRoute =
  GroepenkastVervangenAmsterdamRouteImport.update({
    id: '/groepenkast-vervangen-amsterdam',
    path: '/groepenkast-vervangen-amsterdam',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnGbRoute = EnGbRouteImport.update({
  id: '/en-gb',
  path: '/en-gb',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektricienAmsterdamRoute = ElektricienAmsterdamRouteImport.update({
  id: '/elektricien-amsterdam',
  path: '/elektricien-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektricienRoute = ElektricienRouteImport.update({
  id: '/elektricien',
  path: '/elektricien',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GroepenkastAmsterdamRoute = GroepenkastAmsterdamRouteImport.update({
  id: '/Groepenkast-Amsterdam',
  path: '/Groepenkast-Amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGbIndexRoute = EnGbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnGbRoute,
} as any)
const EnGbStroomstoringAmsterdamRoute =
  EnGbStroomstoringAmsterdamRouteImport.update({
    id: '/stroomstoring-amsterdam',
    path: '/stroomstoring-amsterdam',
    getParentRoute: () => EnGbRoute,
  } as any)
const EnGbSpoedElektricienAmsterdamRoute =
  EnGbSpoedElektricienAmsterdamRouteImport.update({
    id: '/spoed-elektricien-amsterdam',
    path: '/spoed-elektricien-amsterdam',
    getParentRoute: () => EnGbRoute,
  } as any)
const EnGbPerilexAmsterdamRoute = EnGbPerilexAmsterdamRouteImport.update({
  id: '/perilex-amsterdam',
  path: '/perilex-amsterdam',
  getParentRoute: () => EnGbRoute,
} as any)
const EnGbOverOnsRoute = EnGbOverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => EnGbRoute,
} as any)
const EnGbGroepenkastVervangenAmsterdamRoute =
  EnGbGroepenkastVervangenAmsterdamRouteImport.update({
    id: '/groepenkast-vervangen-amsterdam',
    path: '/groepenkast-vervangen-amsterdam',
    getParentRoute: () => EnGbRoute,
  } as any)
const EnGbElektricienAmsterdamRoute =
  EnGbElektricienAmsterdamRouteImport.update({
    id: '/elektricien-amsterdam',
    path: '/elektricien-amsterdam',
    getParentRoute: () => EnGbRoute,
  } as any)
const EnGbContactRoute = EnGbContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnGbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Groepenkast-Amsterdam': typeof GroepenkastAmsterdamRoute
  '/contact': typeof ContactRoute
  '/elektricien': typeof ElektricienRoute
  '/elektricien-amsterdam': typeof ElektricienAmsterdamRoute
  '/en-gb': typeof EnGbRouteWithChildren
  '/groepenkast-vervangen-amsterdam': typeof GroepenkastVervangenAmsterdamRoute
  '/onze-services': typeof OnzeServicesRoute
  '/over-ons': typeof OverOnsRoute
  '/perilex-aansluiten-amsterdam': typeof PerilexAansluitenAmsterdamRoute
  '/perilex-amsterdam': typeof PerilexAmsterdamRoute
  '/postocode-check': typeof PostocodeCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spoed-elektricien-amsterdam': typeof SpoedElektricienAmsterdamRoute
  '/stroomstoring-amsterdam': typeof StroomstoringAmsterdamRoute
  '/en-gb/contact': typeof EnGbContactRoute
  '/en-gb/elektricien-amsterdam': typeof EnGbElektricienAmsterdamRoute
  '/en-gb/groepenkast-vervangen-amsterdam': typeof EnGbGroepenkastVervangenAmsterdamRoute
  '/en-gb/over-ons': typeof EnGbOverOnsRoute
  '/en-gb/perilex-amsterdam': typeof EnGbPerilexAmsterdamRoute
  '/en-gb/spoed-elektricien-amsterdam': typeof EnGbSpoedElektricienAmsterdamRoute
  '/en-gb/stroomstoring-amsterdam': typeof EnGbStroomstoringAmsterdamRoute
  '/en-gb/': typeof EnGbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Groepenkast-Amsterdam': typeof GroepenkastAmsterdamRoute
  '/contact': typeof ContactRoute
  '/elektricien': typeof ElektricienRoute
  '/elektricien-amsterdam': typeof ElektricienAmsterdamRoute
  '/groepenkast-vervangen-amsterdam': typeof GroepenkastVervangenAmsterdamRoute
  '/onze-services': typeof OnzeServicesRoute
  '/over-ons': typeof OverOnsRoute
  '/perilex-aansluiten-amsterdam': typeof PerilexAansluitenAmsterdamRoute
  '/perilex-amsterdam': typeof PerilexAmsterdamRoute
  '/postocode-check': typeof PostocodeCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spoed-elektricien-amsterdam': typeof SpoedElektricienAmsterdamRoute
  '/stroomstoring-amsterdam': typeof StroomstoringAmsterdamRoute
  '/en-gb/contact': typeof EnGbContactRoute
  '/en-gb/elektricien-amsterdam': typeof EnGbElektricienAmsterdamRoute
  '/en-gb/groepenkast-vervangen-amsterdam': typeof EnGbGroepenkastVervangenAmsterdamRoute
  '/en-gb/over-ons': typeof EnGbOverOnsRoute
  '/en-gb/perilex-amsterdam': typeof EnGbPerilexAmsterdamRoute
  '/en-gb/spoed-elektricien-amsterdam': typeof EnGbSpoedElektricienAmsterdamRoute
  '/en-gb/stroomstoring-amsterdam': typeof EnGbStroomstoringAmsterdamRoute
  '/en-gb': typeof EnGbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Groepenkast-Amsterdam': typeof GroepenkastAmsterdamRoute
  '/contact': typeof ContactRoute
  '/elektricien': typeof ElektricienRoute
  '/elektricien-amsterdam': typeof ElektricienAmsterdamRoute
  '/en-gb': typeof EnGbRouteWithChildren
  '/groepenkast-vervangen-amsterdam': typeof GroepenkastVervangenAmsterdamRoute
  '/onze-services': typeof OnzeServicesRoute
  '/over-ons': typeof OverOnsRoute
  '/perilex-aansluiten-amsterdam': typeof PerilexAansluitenAmsterdamRoute
  '/perilex-amsterdam': typeof PerilexAmsterdamRoute
  '/postocode-check': typeof PostocodeCheckRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spoed-elektricien-amsterdam': typeof SpoedElektricienAmsterdamRoute
  '/stroomstoring-amsterdam': typeof StroomstoringAmsterdamRoute
  '/en-gb/contact': typeof EnGbContactRoute
  '/en-gb/elektricien-amsterdam': typeof EnGbElektricienAmsterdamRoute
  '/en-gb/groepenkast-vervangen-amsterdam': typeof EnGbGroepenkastVervangenAmsterdamRoute
  '/en-gb/over-ons': typeof EnGbOverOnsRoute
  '/en-gb/perilex-amsterdam': typeof EnGbPerilexAmsterdamRoute
  '/en-gb/spoed-elektricien-amsterdam': typeof EnGbSpoedElektricienAmsterdamRoute
  '/en-gb/stroomstoring-amsterdam': typeof EnGbStroomstoringAmsterdamRoute
  '/en-gb/': typeof EnGbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Groepenkast-Amsterdam'
    | '/contact'
    | '/elektricien'
    | '/elektricien-amsterdam'
    | '/en-gb'
    | '/groepenkast-vervangen-amsterdam'
    | '/onze-services'
    | '/over-ons'
    | '/perilex-aansluiten-amsterdam'
    | '/perilex-amsterdam'
    | '/postocode-check'
    | '/sitemap.xml'
    | '/spoed-elektricien-amsterdam'
    | '/stroomstoring-amsterdam'
    | '/en-gb/contact'
    | '/en-gb/elektricien-amsterdam'
    | '/en-gb/groepenkast-vervangen-amsterdam'
    | '/en-gb/over-ons'
    | '/en-gb/perilex-amsterdam'
    | '/en-gb/spoed-elektricien-amsterdam'
    | '/en-gb/stroomstoring-amsterdam'
    | '/en-gb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Groepenkast-Amsterdam'
    | '/contact'
    | '/elektricien'
    | '/elektricien-amsterdam'
    | '/groepenkast-vervangen-amsterdam'
    | '/onze-services'
    | '/over-ons'
    | '/perilex-aansluiten-amsterdam'
    | '/perilex-amsterdam'
    | '/postocode-check'
    | '/sitemap.xml'
    | '/spoed-elektricien-amsterdam'
    | '/stroomstoring-amsterdam'
    | '/en-gb/contact'
    | '/en-gb/elektricien-amsterdam'
    | '/en-gb/groepenkast-vervangen-amsterdam'
    | '/en-gb/over-ons'
    | '/en-gb/perilex-amsterdam'
    | '/en-gb/spoed-elektricien-amsterdam'
    | '/en-gb/stroomstoring-amsterdam'
    | '/en-gb'
  id:
    | '__root__'
    | '/'
    | '/Groepenkast-Amsterdam'
    | '/contact'
    | '/elektricien'
    | '/elektricien-amsterdam'
    | '/en-gb'
    | '/groepenkast-vervangen-amsterdam'
    | '/onze-services'
    | '/over-ons'
    | '/perilex-aansluiten-amsterdam'
    | '/perilex-amsterdam'
    | '/postocode-check'
    | '/sitemap.xml'
    | '/spoed-elektricien-amsterdam'
    | '/stroomstoring-amsterdam'
    | '/en-gb/contact'
    | '/en-gb/elektricien-amsterdam'
    | '/en-gb/groepenkast-vervangen-amsterdam'
    | '/en-gb/over-ons'
    | '/en-gb/perilex-amsterdam'
    | '/en-gb/spoed-elektricien-amsterdam'
    | '/en-gb/stroomstoring-amsterdam'
    | '/en-gb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroepenkastAmsterdamRoute: typeof GroepenkastAmsterdamRoute
  ContactRoute: typeof ContactRoute
  ElektricienRoute: typeof ElektricienRoute
  ElektricienAmsterdamRoute: typeof ElektricienAmsterdamRoute
  EnGbRoute: typeof EnGbRouteWithChildren
  GroepenkastVervangenAmsterdamRoute: typeof GroepenkastVervangenAmsterdamRoute
  OnzeServicesRoute: typeof OnzeServicesRoute
  OverOnsRoute: typeof OverOnsRoute
  PerilexAansluitenAmsterdamRoute: typeof PerilexAansluitenAmsterdamRoute
  PerilexAmsterdamRoute: typeof PerilexAmsterdamRoute
  PostocodeCheckRoute: typeof PostocodeCheckRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpoedElektricienAmsterdamRoute: typeof SpoedElektricienAmsterdamRoute
  StroomstoringAmsterdamRoute: typeof StroomstoringAmsterdamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stroomstoring-amsterdam': {
      id: '/stroomstoring-amsterdam'
      path: '/stroomstoring-amsterdam'
      fullPath: '/stroomstoring-amsterdam'
      preLoaderRoute: typeof StroomstoringAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoed-elektricien-amsterdam': {
      id: '/spoed-elektricien-amsterdam'
      path: '/spoed-elektricien-amsterdam'
      fullPath: '/spoed-elektricien-amsterdam'
      preLoaderRoute: typeof SpoedElektricienAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postocode-check': {
      id: '/postocode-check'
      path: '/postocode-check'
      fullPath: '/postocode-check'
      preLoaderRoute: typeof PostocodeCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perilex-amsterdam': {
      id: '/perilex-amsterdam'
      path: '/perilex-amsterdam'
      fullPath: '/perilex-amsterdam'
      preLoaderRoute: typeof PerilexAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perilex-aansluiten-amsterdam': {
      id: '/perilex-aansluiten-amsterdam'
      path: '/perilex-aansluiten-amsterdam'
      fullPath: '/perilex-aansluiten-amsterdam'
      preLoaderRoute: typeof PerilexAansluitenAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onze-services': {
      id: '/onze-services'
      path: '/onze-services'
      fullPath: '/onze-services'
      preLoaderRoute: typeof OnzeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groepenkast-vervangen-amsterdam': {
      id: '/groepenkast-vervangen-amsterdam'
      path: '/groepenkast-vervangen-amsterdam'
      fullPath: '/groepenkast-vervangen-amsterdam'
      preLoaderRoute: typeof GroepenkastVervangenAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-gb': {
      id: '/en-gb'
      path: '/en-gb'
      fullPath: '/en-gb'
      preLoaderRoute: typeof EnGbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektricien-amsterdam': {
      id: '/elektricien-amsterdam'
      path: '/elektricien-amsterdam'
      fullPath: '/elektricien-amsterdam'
      preLoaderRoute: typeof ElektricienAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektricien': {
      id: '/elektricien'
      path: '/elektricien'
      fullPath: '/elektricien'
      preLoaderRoute: typeof ElektricienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Groepenkast-Amsterdam': {
      id: '/Groepenkast-Amsterdam'
      path: '/Groepenkast-Amsterdam'
      fullPath: '/Groepenkast-Amsterdam'
      preLoaderRoute: typeof GroepenkastAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-gb/': {
      id: '/en-gb/'
      path: '/'
      fullPath: '/en-gb/'
      preLoaderRoute: typeof EnGbIndexRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/stroomstoring-amsterdam': {
      id: '/en-gb/stroomstoring-amsterdam'
      path: '/stroomstoring-amsterdam'
      fullPath: '/en-gb/stroomstoring-amsterdam'
      preLoaderRoute: typeof EnGbStroomstoringAmsterdamRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/spoed-elektricien-amsterdam': {
      id: '/en-gb/spoed-elektricien-amsterdam'
      path: '/spoed-elektricien-amsterdam'
      fullPath: '/en-gb/spoed-elektricien-amsterdam'
      preLoaderRoute: typeof EnGbSpoedElektricienAmsterdamRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/perilex-amsterdam': {
      id: '/en-gb/perilex-amsterdam'
      path: '/perilex-amsterdam'
      fullPath: '/en-gb/perilex-amsterdam'
      preLoaderRoute: typeof EnGbPerilexAmsterdamRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/over-ons': {
      id: '/en-gb/over-ons'
      path: '/over-ons'
      fullPath: '/en-gb/over-ons'
      preLoaderRoute: typeof EnGbOverOnsRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/groepenkast-vervangen-amsterdam': {
      id: '/en-gb/groepenkast-vervangen-amsterdam'
      path: '/groepenkast-vervangen-amsterdam'
      fullPath: '/en-gb/groepenkast-vervangen-amsterdam'
      preLoaderRoute: typeof EnGbGroepenkastVervangenAmsterdamRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/elektricien-amsterdam': {
      id: '/en-gb/elektricien-amsterdam'
      path: '/elektricien-amsterdam'
      fullPath: '/en-gb/elektricien-amsterdam'
      preLoaderRoute: typeof EnGbElektricienAmsterdamRouteImport
      parentRoute: typeof EnGbRoute
    }
    '/en-gb/contact': {
      id: '/en-gb/contact'
      path: '/contact'
      fullPath: '/en-gb/contact'
      preLoaderRoute: typeof EnGbContactRouteImport
      parentRoute: typeof EnGbRoute
    }
  }
}

interface EnGbRouteChildren {
  EnGbContactRoute: typeof EnGbContactRoute
  EnGbElektricienAmsterdamRoute: typeof EnGbElektricienAmsterdamRoute
  EnGbGroepenkastVervangenAmsterdamRoute: typeof EnGbGroepenkastVervangenAmsterdamRoute
  EnGbOverOnsRoute: typeof EnGbOverOnsRoute
  EnGbPerilexAmsterdamRoute: typeof EnGbPerilexAmsterdamRoute
  EnGbSpoedElektricienAmsterdamRoute: typeof EnGbSpoedElektricienAmsterdamRoute
  EnGbStroomstoringAmsterdamRoute: typeof EnGbStroomstoringAmsterdamRoute
  EnGbIndexRoute: typeof EnGbIndexRoute
}

const EnGbRouteChildren: EnGbRouteChildren = {
  EnGbContactRoute: EnGbContactRoute,
  EnGbElektricienAmsterdamRoute: EnGbElektricienAmsterdamRoute,
  EnGbGroepenkastVervangenAmsterdamRoute:
    EnGbGroepenkastVervangenAmsterdamRoute,
  EnGbOverOnsRoute: EnGbOverOnsRoute,
  EnGbPerilexAmsterdamRoute: EnGbPerilexAmsterdamRoute,
  EnGbSpoedElektricienAmsterdamRoute: EnGbSpoedElektricienAmsterdamRoute,
  EnGbStroomstoringAmsterdamRoute: EnGbStroomstoringAmsterdamRoute,
  EnGbIndexRoute: EnGbIndexRoute,
}

const EnGbRouteWithChildren = EnGbRoute._addFileChildren(EnGbRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroepenkastAmsterdamRoute: GroepenkastAmsterdamRoute,
  ContactRoute: ContactRoute,
  ElektricienRoute: ElektricienRoute,
  ElektricienAmsterdamRoute: ElektricienAmsterdamRoute,
  EnGbRoute: EnGbRouteWithChildren,
  GroepenkastVervangenAmsterdamRoute: GroepenkastVervangenAmsterdamRoute,
  OnzeServicesRoute: OnzeServicesRoute,
  OverOnsRoute: OverOnsRoute,
  PerilexAansluitenAmsterdamRoute: PerilexAansluitenAmsterdamRoute,
  PerilexAmsterdamRoute: PerilexAmsterdamRoute,
  PostocodeCheckRoute: PostocodeCheckRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpoedElektricienAmsterdamRoute: SpoedElektricienAmsterdamRoute,
  StroomstoringAmsterdamRoute: StroomstoringAmsterdamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
